Feladat 4: refractoring
Teaching-projects/SZE-MOSZE-2020-VoicePlay pull request #10
Opened 2020-11-01 13:39 UTC by vbence121

2020-11-02 00:24 UTC, hegyhati requested changes
Az egesz JSON-osdit tessek atgondolni, egy nagyon nagy katyvasz most.

2020-11-02 00:24 UTC, hegyhati commented on JSON.h
> +    }
No, a JSON parser semmilyen hero-rol meg monsterrol nem tudhat, illetve ennek igy semmi ertelme nincs.

2020-11-02 00:24 UTC, hegyhati commented on Monster.h
> +        return Monster(n, h, d, a);
na ennek kellene annyinak lennie, hogy `n=get<string>("name"); d=get<int>("damage"),...`

2020-11-02 00:24 UTC, hegyhati commented on JSON.h
> +    }
na ilyet tipikusan nem kitenni publicba.

2020-11-03 09:29 UTC, hegyhati requested changes
A lenyeg nem jott at. A kriptikus fuggvenyneveket felejtsuk el public interface-ben. A main.cpp lenyege az volt, hogy kieroszakoljon egy letisztult parzolast:

`JSON ize=JSON::parse(filename)` visszaad egy json objektumot. Ebbol get-tel szepen lekerheto minden kulcshoz az ertek. Ennyi. tobb public dolog nincs (leszamitva a stream konstruktort, stb.) 

Nem egy plusz osztalyt kell irni a JSONParser melle, azt kellet refaktoralni. Ha meghagyjatok a "worker" osztalynak a JSON melle, nem ertem, miert, de ok. De akkor az egy privat subclass legyen, amit csak a JSON lat. A Hero es a tobbiek a fenti letisztult interfeszt hasznaljak a parzolashoz.

2020-11-03 10:23 UTC, vbence121 commented
Szerintem értem így már nagyjából mire gondolt. A `try{
            m = JSONparser::fileInp(fname);
        }catch(const std::string e){
                std::cerr << e << '\n';
                std::exit( -1);
        }`   kód a monster/hero/unit parse fugvényében valóban "felhasználja" de ezzel az adattal műveletet nem végez, csupán véletlenül bent maradt a kód és mivel hibát nem okozott nem tűnt fel idáig az itt deklarált 'm' helyett az adatok a később létre hozott `JSON attributes = JSON::parseFromFile(fname);`-ból származnak. Minden esetre valóban nem szép.

> Ha meghagyjatok a "worker" osztalynak a JSON melle, nem ertem, miert, de ok.

Az oka, ami miatt e mellett döntöttem szimplán az volt hogy a már meglévő unit testek többször is felhasználták ezt az osztályt és ha ez nem elérhető publikusan a már meglévő közel 20 tesztből sok megoldhatatlan lenne és szimplán ki lehetne törölni.

Minden esetre a JSONparser most már egy private subclass-a a JSON-nek és az egyedüli publikus részek a JSON.h-ban a `parseFromFile(filename),` `get<typename>(key),` `count(key)` és a `ParseException` amiket a main ténylegesen használ. 
Ezt nem gondolnám én sem feltétlenül egy "végleges" megoldásnak inkább csak egy visszaigazolás hogy jó vonalon indultam-e el, sikerült-e megérteni az elvárt változtatásokat. (Korábbi "félelmeimmel" ellentétben csak egy unit test-ben okozott problémámat a változtatás, ezt ki kellettem kommentelni mivel lehetetlen a teszt sikeres lefutása a JSONparser publikus stringinput fugvénye nélkül"

2020-11-03 10:31 UTC, hegyhati commented
Ahoj. Igen, szerintem ez igy jonak tunik, nyilvan a GHA-kat pofozd helyre, meg a kodszemetet torold ki. Bevallom, a unit testekhez anyira nem ertek, most jobban at kellene neznem, de valahogy biztosan meg lehet oldani, hogy hozaferjen a dolgokhoz anelkul, hogy a fo kodban ez ne jelentene szuksegtelen "plusz feluletet". De amugy 1 teszt ha elveszett, az meg turtheto. Lehet amugy csinalni az "uj" JSON-nek egy parseFromString-et, vagy akar a sima parse, csak monjduk van egy argumentum ertek, hogy filenev-ken vagy adatkent ertelmezze. Vag ycsinalni egy JSONString osztalyt, ami csak egy alias a string-re, es egy parse(JSONString)-et, (Utobbi a legszebb).

2020-11-03 11:58 UTC, vbence121 commented
Kelett hozzá pár commit, de kitisztult egy kicsit a kód és lefutnak a GHA-k.

2020-11-04 16:19 UTC, hegyhati requested changes
A bentmaradt kodszemeteket torold ki, amugy utana mar mehet be. (Monster.h pl)

2020-11-04 16:28 UTC, vbence121 commented
Ups, elnézést a Monster.h-ban véletlen tényleg bent maradt, törölve.

2020-11-04 16:29 UTC, vbence121 commented
A tesztek nem a mi hibánkból hasaltak el. Valamiért a rendszer nem tudott csatlakozni egy külső szerverhez.

2020-11-04 17:21 UTC, hegyhati approved these changes

2020-11-04 17:23 UTC, merged