Docker
Teaching-projects/SZE-MOSZE-2020-VoicePlay pull request #12
Opened 2020-11-10 12:49 UTC by kkira07

Docker images ok, workflow runs

2020-11-11 10:38 UTC, kkira07 commented
@hegyhati
Volt a pr után egy apróbb módosítás (korábban a yml fájlonként való tesztelgetés miatt elfelejtettem hozzáadni a push-olt dolgokhoz a docker image-ket), de elvileg már elbírálásra kész a feladat

2020-11-12 09:24 UTC, hegyhati requested changes
Azt a deply-os dolgot tessek rendbetenni, amugy ok.

2020-11-12 09:24 UTC, hegyhati commented on .github/workflows/doxy.yml
> -      - gh-pages
most akkro minden branchen vegbemegy?! az ugy nagyon nem lesz jo, csak a masteren kellene

2020-11-12 19:31 UTC, kkira07 commented
@hegyhati  Javítva. A review-t újrakértem javításkor, csak gondoltam írok, hátha esetleg nem látta.

2020-11-13 18:48 UTC, hegyhati approved these changes

2020-11-13 18:48 UTC, merged