Json pimp feladat
Teaching-projects/SZE-MOSZE-2020-VoicePlay pull request #13
Opened 2020-11-17 20:52 UTC by vbence121

2020-11-18 09:13 UTC, eriklorincz requested changes
Nagyjából jónak, tűnik de azért lehet rajta szépíteni. A debuggolásból megmaradt kicommentelt sorokat néhány helyen megjelöltem, de van még ezeken kívül is. Szedjétek ki mindet, a masterbe már ne így menjen be.

2020-11-18 09:13 UTC, eriklorincz commented on JSON.cpp
> +            //std::cout << t << "\n";
Kódszemetet ne hagyjunk bent.

2020-11-18 09:13 UTC, eriklorincz commented on Hero.cpp
> +        //std::cout << "parse f"<< "\neddig ok\n";
Erre itt nincs szükség.

2020-11-18 09:13 UTC, eriklorincz commented on JSON.cpp
> +                        //std::cout << val << "\neddig ok [ val outside \n";
Kódszemét

2020-11-18 09:13 UTC, eriklorincz commented on JSON.h
> +    }
Ez a függvény ránézésre nyugodtan lehetne private is.

2020-11-18 09:13 UTC, eriklorincz commented on JSON.cpp
> +#include <variant>
Ezeket már a header-ben is ugyanígy include-oltad. Nézd meg, hogy melyikre hol van először szükség és csak ott maradjon bent.

2020-11-18 09:13 UTC, eriklorincz commented on JSON.cpp
> +            }
Ezt azért vesézzük ki egy kicsit. Ha már van exception header-ünk, nyugodtan dobálhatnánk kivételeket is, de ez csak egy megjegyzés. 
Összetett típusok esetén kell referencia szerint elkapni, inteknél olyan túl sok értelme nincsen.
Ha az érzékeim nem csalnak akkor a `case -2:` re semmi szükséged nincsen. Ehhez kapcsolódó bónusz tipp: Kódszemét!

2020-11-18 09:13 UTC, eriklorincz commented on JSON.h
> +        std::ifstream f(fname);
Kódszemét

2020-11-18 09:13 UTC, eriklorincz commented on main.cpp
> +                //std::cout << "inside"<< "\neddig ok\n";
Nicsak még egy kis kódszemét. Ráadásul a main-ben.

2020-11-18 10:15 UTC, eriklorincz approved these changes
Így már OK.

2020-11-18 10:23 UTC, kalmar-adam approved these changes
Ez így már szebb a nagytakarítás után. Jó lesz ez.

2020-11-20 12:39 UTC, kkira07 approved these changes

2020-11-25 13:40 UTC, merged