Prepared game
Teaching-projects/SZE-MOSZE-2020-VoicePlay pull request #18
Opened 2020-12-03 10:02 UTC by vbence121

2020-12-04 10:17 UTC, eriklorincz requested changes
Nem mondom hogy minden részét értem, de remélhetőleg teszi a dolgát. Azt az egy felesleges dolgot vegyétek ki, aztán elfogadom.

2020-12-04 10:17 UTC, eriklorincz commented on Mmap.h
> +                    break;
Prepared Game esetén már csak egy Monster lehet egy helyen. A `multMonsterPresent` ágra nincs szükség.

2020-12-05 09:53 UTC, eriklorincz approved these changes
Rendben

2020-12-05 09:58 UTC, kalmar-adam approved these changes
nice.

2020-12-06 13:07 UTC, kkira07 approved these changes

2020-12-06 13:08 UTC, merged