Lightradius done
Teaching-projects/SZE-MOSZE-2020-VoicePlay pull request #19
Opened 2020-12-04 15:49 UTC by vbence121

2020-12-05 09:02 UTC, eriklorincz requested changes
Az még nem baj, hogy a json-ben nincs `light_radius_bonus_per_level`, hiszen a feladat megenged ilyen esetet. Azonban ha jól látom sehol nem implementáltátok ha netán mégis lenne.

2020-12-05 09:02 UTC, eriklorincz commented on Hero.h
>      void heal(double d) {   //heal unit to d hp
Nem látok `light_radius_bonus_per_level` attribútumot.

2020-12-05 09:02 UTC, eriklorincz commented on Dark_Wanderer.json
>  }
A feladatkiírás szerint a kulcs `light_radius`

2020-12-05 09:02 UTC, eriklorincz commented on Hero.cpp
Itt is `light_radius`

2020-12-06 13:06 UTC, kkira07 approved these changes

2020-12-06 13:08 UTC, eriklorincz approved these changes
OK

2020-12-06 13:33 UTC, merged